Teste automatizar deploy no render

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -141,6 +141,16 @@ jobs:
       name: dev
     if: github.ref == 'refs/heads/develop'
     steps:
+      - uses: actions/checkout@v3
+      - uses: JorgeLNJunior/render-deploy@v1.4.4
+        with:
+          service_id: ${{ secrets.RENDER_SERVICE_ID }}
+          api_key: ${{ secrets.RENDER_API_KEY }}
+          clear_cache: true
+          wait_deploy: true
+          github_deployment: true
+          deployment_environment: dev
+          github_token: ${{ secrets.GITHUB_TOKEN }}
       - name: Deploy
         shell: bash
         run: |
@@ -150,23 +160,34 @@ jobs:
     name: Health check application
     runs-on: ubuntu-latest
     needs: [ deploy-develop,deploy-prod ]
-    if: always()
+    if: always() && (needs.deploy-develop.result == 'success' || needs.deploy-prod.result == 'success')
     steps:
       - uses: actions/checkout@v3
-      - name: Deploy
+      - name: Health check application
         shell: bash
-        run: echo "Call http://localhost:8080/health"
+        run: |
+          if curl -f -s -o /dev/null https://med-api-tq4u.onrender.com/actuator/health; then
+            echo "UP"
+          else
+            echo "DOWN" && exit 1
+          fi
 
-  response-ok:
-    name: Response OK
+  call-api:
+    name: Call API
     runs-on: ubuntu-latest
     needs: health-check-app
     if: always() && needs.health-check-app.result == 'success'
     steps:
       - uses: actions/checkout@v3
-      - name: Deploy
+      - name: Call API
         shell: bash
-        run: echo "Call http://localhost:8080/ping"
+        run: |
+          response=$(curl -s https://med-api-tq4u.onrender.com/ping)
+          if [ "$?" -eq 0 ]; then
+            echo "Response:$response"
+          else
+            echo "Error in deploy" && exit 1
+          fi
 
   deploy-prod:
     name: Deploy prod
